# Generated by Django 2.1 on 2020-05-07 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sump', models.IntegerField(blank=True, default=0, verbose_name='收藏人数')),
                ('new_books', models.BooleanField(blank=True, default=False, verbose_name='新书')),
                ('title', models.CharField(blank=True, max_length=32, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='作者')),
                ('book_star', models.CharField(blank=True, max_length=32, verbose_name='评分')),
                ('book_pl', models.IntegerField(blank=True, default=0, verbose_name='评价人数')),
                ('book_publish', models.CharField(blank=True, max_length=32, verbose_name='出版社')),
                ('book_date', models.CharField(blank=True, max_length=32, verbose_name='出版日期')),
                ('book_price', models.CharField(blank=True, max_length=32, verbose_name='价格')),
                ('intro', models.TextField(blank=True, verbose_name='描述')),
                ('num', models.IntegerField(blank=True, default=0, verbose_name='浏览量')),
                ('pic', models.FileField(max_length=64, upload_to='book_cover', verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.IntegerField(default=0, verbose_name='点赞')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Book', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Book', verbose_name='图书id')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名字')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='book',
            name='collect',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='user.Tags', verbose_name='标签'),
        ),
    ]
