# Generated by Django 2.1 on 2020-05-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200507_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='mark',
            field=models.IntegerField(verbose_name='评分'),
        ),
    ]
